
spring:
  application:
    name: product

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

custom:
  message: "Hello and welcome from Product Service via Config Server"
