server:
  port: 8072

spring:
  application:
    name: user

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

custom:
  message: "Hello  from User Service via Config Server."
